/**
 * The versioned Provider/Reader migration matrix, grounded in the code as it is
 * on this branch. Every existing analysis unit has exactly one home, so a later
 * agent extends the existing emitter instead of writing a parallel one.
 */

import type { MigrationMatrix, ProviderUnit } from "./schema.js";

const UNITS: readonly ProviderUnit[] = [
  {
    id: "codegraph",
    files: ["engine/providers/codegraph/provider.ts", "engine/providers/codegraph/normalize.ts"],
    role: "provider",
    factKinds: ["symbol", "import", "route", "call-edge"],
    registered: true,
    consumers: ["engine/kb/build.ts", "engine/structural/assemble.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-5", "PI-6", "PI-34", "PI-35", "PI-36", "PI-7"],
    forbiddenParallel: "a second structural graph or a parallel symbol/edge store",
    note: "default path forces callEdges:false and skips symbols for AST languages; opening capability must obey the identity/merge contract, not just flip the flag",
  },
  {
    id: "sourcefiles",
    files: ["engine/providers/sourcefiles/provider.ts"],
    role: "provider",
    factKinds: ["source-file"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: false,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-5", "PI-7"],
    forbiddenParallel: "a parallel source-file inventory",
  },
  {
    id: "symbols",
    files: ["engine/providers/symbols/provider.ts"],
    role: "provider",
    factKinds: ["symbol", "import"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-5", "PI-57"],
    forbiddenParallel: "a parallel symbol reader; symbol identity is canonical",
    note: "in-process ast-grep; Go/TS/JS/TSX; no cross-file resolution",
  },
  {
    id: "manifests",
    files: ["engine/providers/manifests/provider.ts"],
    role: "provider",
    factKinds: ["package-dependency", "build-target", "module-containment"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-5", "PI-76"],
    forbiddenParallel: "a parallel dependency/module-containment reader",
  },
  {
    id: "logic",
    files: ["engine/providers/logic/provider.ts", "engine/providers/logic/decisions.ts"],
    role: "provider",
    factKinds: ["condition", "decision", "guard", "discarded-error"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "retain",
    action: "extend",
    targetIssues: ["PI-11", "PI-37"],
    forbiddenParallel: "a parallel condition/decision/rule provider",
  },
  {
    id: "outbound",
    files: ["engine/providers/outbound/provider.ts"],
    role: "provider",
    factKinds: ["outbound-call"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-12"],
    forbiddenParallel: "a parallel outbound-call provider; keep dynamic targets unresolved",
  },
  {
    id: "uicalls",
    files: ["engine/providers/uicalls/provider.ts"],
    role: "provider",
    factKinds: ["outbound-call"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-12"],
    forbiddenParallel: "a parallel UI-call provider",
  },
  {
    id: "conventions",
    files: ["engine/providers/conventions/provider.ts", "engine/providers/conventions/patterns.ts"],
    role: "enricher",
    factKinds: [
      "validation-rule",
      "transaction-boundary",
      "error-handling",
      "auth-annotation",
      "notification-call",
      "scheduled-task",
      "data-access",
    ],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "enricher",
    action: "adapt",
    targetIssues: ["PI-11", "PI-12", "PI-39"],
    forbiddenParallel: "letting heuristic conventions override resolved evidence; results stay inferred/candidate",
    note: "heuristic; its data-access always has entity=null (weak), superseded by datamodel-usage",
  },
  {
    id: "frameworkroutes",
    files: [
      "engine/providers/frameworkroutes/provider.ts",
      "engine/providers/frameworkroutes/readers/gin.ts",
      "engine/providers/frameworkroutes/readers/express.ts",
      "engine/providers/frameworkroutes/readers/reactrouter.ts",
    ],
    role: "enricher",
    factKinds: ["route"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "enricher",
    action: "adapt",
    targetIssues: ["PI-27", "PI-28", "PI-10"],
    forbiddenParallel: "treating framework readers as the only route source; the generic path must work with no reader",
    note: "Gin/Express/React Router only",
  },
  {
    id: "datamodel-usage",
    files: ["engine/datamodel/usage.ts"],
    role: "provider",
    factKinds: ["data-access"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: false,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-12", "PI-9"],
    forbiddenParallel: "a parallel data-access provider",
    note: "authoritative data-access — resolves code refs to physical tables",
  },
  {
    id: "datamodel-sql",
    files: ["engine/datamodel/sql.ts"],
    role: "provider",
    factKinds: ["entity", "entity-field", "entity-relation", "entity-constraint"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-9", "PI-12"],
    forbiddenParallel: "a parallel entity/schema provider; entities merge by canonical name",
  },
  {
    id: "datamodel-orm",
    files: ["engine/datamodel/orm.ts"],
    role: "provider",
    factKinds: ["entity", "entity-field", "entity-relation", "entity-constraint"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-9"],
    forbiddenParallel: "a parallel ORM/entity provider",
  },
  {
    id: "datamodel-gostructs",
    files: ["engine/datamodel/gostructs.ts"],
    role: "provider",
    factKinds: ["entity", "entity-field", "entity-constraint"],
    registered: true,
    consumers: ["engine/kb/build.ts"],
    hasTests: false,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-9"],
    forbiddenParallel: "a parallel Go-model entity provider",
  },
  {
    id: "documentation",
    files: ["engine/collectors/documentation.ts"],
    role: "collector",
    factKinds: ["project-title", "project-description", "readme-section", "config-key"],
    registered: true,
    consumers: ["engine/kb/build.ts", "engine/semantic/assemble.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-11"],
    forbiddenParallel: "drawing product conclusions inside the collector",
  },
  {
    id: "code-text",
    files: ["engine/collectors/code.ts"],
    role: "collector",
    factKinds: ["doc-comment", "test-name", "ui-label"],
    registered: true,
    consumers: ["engine/kb/build.ts", "engine/semantic/assemble.ts"],
    hasTests: true,
    home: "retain",
    action: "adapt",
    targetIssues: ["PI-11"],
    forbiddenParallel: "a parallel code-text collector",
  },
  {
    id: "semantics-enums",
    files: ["engine/semantics/enums.ts"],
    role: "deriver",
    factKinds: ["value-set"],
    registered: false,
    consumers: ["engine/kb/extract.ts"],
    hasTests: true,
    home: "adapt",
    action: "adapt",
    targetIssues: ["PI-38", "PI-11"],
    forbiddenParallel: "a parallel value-set/enum deriver",
    note: "KB-layer deriver (not in defaultReaders); Go const/iota, TS enum, const objects",
  },
  {
    id: "semantics-rules",
    files: ["engine/semantics/rules.ts"],
    role: "deriver",
    factKinds: ["business-rule"],
    registered: false,
    consumers: ["engine/kb/derive.ts"],
    hasTests: true,
    home: "adapt",
    action: "adapt",
    targetIssues: ["PI-37", "PI-11"],
    forbiddenParallel: "a parallel rule deriver",
    note: "KB-layer deriver; joins a condition to its value-set",
  },
  {
    id: "tests",
    files: ["engine/providers/tests/provider.ts"],
    role: "deriver",
    factKinds: ["test-relation"],
    registered: false,
    consumers: [],
    hasTests: false,
    home: "adapt",
    action: "integrate",
    targetIssues: ["PI-40"],
    forbiddenParallel: "a parallel test-relation provider",
    note: "exists but unregistered; consumes assembled symbols+call-edges (which the default codegraph run disables). PI-40 must reuse its capability or give an explicit replace+delete plan",
  },
  {
    id: "fake",
    files: ["engine/providers/fake/provider.ts"],
    role: "test-provider",
    factKinds: [],
    registered: false,
    consumers: ["tests/structural/*"],
    hasTests: false,
    home: "test-only",
    action: "adapt",
    targetIssues: [],
    forbiddenParallel: "entering the production default path",
    note: "in-memory fixture provider; test use only",
  },
  {
    id: "state-transition",
    files: ["engine/providers/state/provider.ts (planned)"],
    role: "deriver",
    factKinds: ["state", "transition"],
    registered: false,
    consumers: [],
    hasTests: false,
    home: "net-new",
    action: "net-new",
    targetIssues: ["PI-38"],
    forbiddenParallel: "conflating state with value-set; building a second state store outside canonical identity",
    note: "no existing emitter — net-new schema + derivation",
  },
];

export const MIGRATION_MATRIX: MigrationMatrix = {
  version: "1.0.0",
  units: UNITS,
};
