import { describe, expect, it } from "vitest";

import { classifyPath, looksGenerated } from "../../engine/inventory/classify.js";

describe("classifyPath — test", () => {
  it("classifies Go test files", () => {
    expect(classifyPath("internal/handler_test.go")).toBe("test");
  });

  it("classifies TS/JS test and spec files", () => {
    expect(classifyPath("src/foo.test.ts")).toBe("test");
    expect(classifyPath("src/foo.spec.ts")).toBe("test");
  });

  it("classifies anything under a test(s) directory", () => {
    expect(classifyPath("test/fixtures/sample.json")).toBe("test");
    expect(classifyPath("tests/support/helper.ts")).toBe("test");
    expect(classifyPath("src/__tests__/thing.ts")).toBe("test");
  });
});

describe("classifyPath — schema-migration", () => {
  it("classifies .sql files", () => {
    expect(classifyPath("db/schema.sql")).toBe("schema-migration");
  });

  it("classifies anything under a migrations directory regardless of extension", () => {
    expect(classifyPath("migrations/0001_init.go")).toBe("schema-migration");
    expect(classifyPath("db/migration/2020_add_column.py")).toBe("schema-migration");
  });
});

describe("classifyPath — configuration", () => {
  it("classifies known config filenames", () => {
    expect(classifyPath("Dockerfile")).toBe("configuration");
    expect(classifyPath("build/Dockerfile")).toBe("configuration");
    expect(classifyPath("bitbucket-pipelines.yml")).toBe("configuration");
    expect(classifyPath("Makefile")).toBe("configuration");
  });

  it("classifies known config extensions", () => {
    expect(classifyPath("config/app.yaml")).toBe("configuration");
    expect(classifyPath("pyproject.toml")).toBe("configuration");
  });

  it("classifies dotenv files by name, without reading their contents", () => {
    expect(classifyPath(".env")).toBe("configuration");
    expect(classifyPath(".env.production")).toBe("configuration");
    expect(classifyPath(".env.example")).toBe("configuration");
  });
});

describe("classifyPath — documentation", () => {
  it("classifies markdown and README variants", () => {
    expect(classifyPath("README.md")).toBe("documentation");
    expect(classifyPath("docs/guide.mdx")).toBe("documentation");
    expect(classifyPath("README")).toBe("documentation");
  });
});

describe("classifyPath — binary-asset", () => {
  it("classifies known binary/asset extensions", () => {
    expect(classifyPath("logo.png")).toBe("binary-asset");
    expect(classifyPath("font.woff2")).toBe("binary-asset");
    expect(classifyPath("archive.zip")).toBe("binary-asset");
  });
});

describe("classifyPath — source", () => {
  it("classifies known source extensions", () => {
    expect(classifyPath("src/index.ts")).toBe("source");
    expect(classifyPath("main.go")).toBe("source");
    expect(classifyPath("app.py")).toBe("source");
  });
});

describe("classifyPath — precedence", () => {
  it("treats a test file inside a migrations directory as a test, not a migration", () => {
    // Test conventions are checked first — a *_test.go under migrations/ is
    // still exercising test code, not declaring schema.
    expect(classifyPath("migrations/apply_test.go")).toBe("test");
  });
});

describe("classifyPath — weak evidence", () => {
  it("returns null for an extensionless file with no other signal", () => {
    // Weak evidence must yield null (→ unknown after a content peek finds
    // nothing), never a guessed classification.
    expect(classifyPath("some/path/LICENSE")).toBeNull();
  });

  it("returns null for an unrecognized extension", () => {
    expect(classifyPath("data.xyz123")).toBeNull();
  });
});

describe("looksGenerated", () => {
  it("recognises the marker confirmed on a real generated file (wcp-auth/docs/docs.go)", () => {
    const prefix = "// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT\n// This file was generated by swaggo/swag\n\npackage docs\n";
    expect(looksGenerated(prefix)).toBe(true);
  });

  it("recognises the Go standard convention", () => {
    expect(looksGenerated("// Code generated by protoc-gen-go. DO NOT EDIT.\n")).toBe(true);
  });

  it("does not flag ordinary source as generated", () => {
    expect(looksGenerated("package main\n\nfunc main() {}\n")).toBe(false);
  });

  it("requires both signals, not just one", () => {
    expect(looksGenerated("// this code was generated once, long ago\n")).toBe(false);
    expect(looksGenerated("// please do not edit this by hand\n")).toBe(false);
  });

  it("only looks at a bounded prefix", () => {
    const farAway = " ".repeat(10_000) + "// generated, do not edit";
    expect(looksGenerated(farAway)).toBe(false);
  });
});
