import { extname, sep } from "node:path";

import { SOURCE_EXTENSIONS } from "../workspace/manifests.js";

/**
 * `"vendored"` is a real category — a single third-party file copied directly
 * into an otherwise ordinary directory, not inside a dependency-manager
 * directory. No path/extension signal reliably distinguishes that from
 * hand-written code, unlike `"generated"`, which has a near-universal marker
 * convention. `classifyPath` does not produce `"vendored"` for that reason —
 * an honest gap, kept in the type rather than removed, the same way the
 * `"unsupported"` disposition is kept with no current producer.
 */
export type Classification =
  | "source"
  | "test"
  | "configuration"
  | "documentation"
  | "schema-migration"
  | "vendored"
  | "generated"
  | "binary-asset"
  | "unknown";

/**
 * Directories populated exclusively by a package manager or build toolchain —
 * never hand-authored. Safe to bulk-exclude without walking their contents.
 *
 * Deliberately narrower than `engine/workspace/manifests.ts`'s
 * `NON_ROOT_DIRECTORIES`, which answers a different question (is this
 * directory a candidate project root?) and includes generic names like
 * `build`/`dist`/`out`/`coverage`/`tmp`. Those are not safe here: real targets
 * in this project have a `build/` directory containing nothing but a
 * hand-written `Dockerfile`. A directory-name rule broad enough to catch that
 * would misclassify real, relevant source as vendored noise — a confident
 * wrong answer, which this project's own honesty rule treats as worse than
 * the small extra cost of walking in and looking.
 */
export const DEPENDENCY_DIRECTORIES: ReadonlySet<string> = new Set([
  "node_modules",
  "bower_components",
  "vendor",
  ".venv",
  "venv",
  "__pycache__",
  "Pods",
  "DerivedData",
]);

const BINARY_ASSET_EXTENSIONS: ReadonlySet<string> = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".bmp", ".svg",
  ".woff", ".woff2", ".ttf", ".otf", ".eot",
  ".zip", ".tar", ".gz", ".rar", ".7z",
  ".pdf", ".mp3", ".mp4", ".mov", ".wav",
  ".so", ".dylib", ".dll", ".exe", ".class", ".jar", ".wasm",
]);

const CONFIG_EXTENSIONS: ReadonlySet<string> = new Set([".yml", ".yaml", ".toml", ".ini", ".cfg"]);
const DOC_EXTENSIONS: ReadonlySet<string> = new Set([".md", ".mdx", ".rst", ".adoc", ".txt"]);

const CONFIG_FILENAMES: ReadonlySet<string> = new Set([
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
  "bitbucket-pipelines.yml",
  "Makefile",
  ".gitignore",
  ".dockerignore",
  ".editorconfig",
]);

function baseName(relPath: string): string {
  const segments = relPath.split(sep);
  return segments[segments.length - 1] ?? relPath;
}

function pathSegmentsLowercase(relPath: string): string[] {
  return relPath.toLowerCase().split(sep);
}

/** True for `.env`, `.env.production`, `.env.local`, and similar. Filename alone — no content is read. */
function looksLikeDotEnv(name: string): boolean {
  return name === ".env" || name.startsWith(".env.");
}

function isTestPath(relPath: string): boolean {
  const name = baseName(relPath).toLowerCase();
  if (/(^|[._-])test[._-]|[._-]test$|\.spec\./.test(name)) return true;
  return pathSegmentsLowercase(relPath).some((seg) => seg === "test" || seg === "tests" || seg === "__tests__");
}

function isMigrationPath(relPath: string): boolean {
  if (extname(relPath).toLowerCase() === ".sql") return true;
  return pathSegmentsLowercase(relPath).some((seg) => seg === "migration" || seg === "migrations");
}

/**
 * Classifies by path and extension alone — the cheap, always-available
 * evidence. Returns `null` when nothing here settles it, meaning the caller
 * should fall back to a bounded content peek (see `looksGenerated`).
 *
 * A `"source"` result is provisional, not final: generated code almost always
 * keeps its language's ordinary extension (confirmed on a real file —
 * `wcp-auth/docs/docs.go` is a `.go` file whose first line reads
 * `GENERATED BY THE COMMAND ABOVE; DO NOT EDIT`), so a caller must still peek
 * for the generated marker before trusting `"source"`. Every other result
 * here is treated as final.
 */
export function classifyPath(relPath: string): Classification | null {
  const name = baseName(relPath);
  const ext = extname(relPath).toLowerCase();

  if (isTestPath(relPath)) return "test";
  if (isMigrationPath(relPath)) return "schema-migration";
  if (CONFIG_FILENAMES.has(name) || CONFIG_EXTENSIONS.has(ext) || looksLikeDotEnv(name)) {
    return "configuration";
  }
  if (DOC_EXTENSIONS.has(ext) || /^readme(\.|$)/i.test(name)) return "documentation";
  if (BINARY_ASSET_EXTENSIONS.has(ext)) return "binary-asset";
  if (SOURCE_EXTENSIONS.has(ext)) return "source";

  return null;
}

/**
 * A well-established, ecosystem-spanning convention: tools that generate code
 * mark it as generated so humans (and now this tool) know not to hand-edit it.
 * Checked only on a small bounded prefix — this never reads or persists a
 * file's full content.
 */
export function looksGenerated(prefix: string): boolean {
  const head = prefix.slice(0, 500);
  return /generated/i.test(head) && /do not edit/i.test(head);
}
